### ISSUE TITLE
An issue after the new Google Drive update

### ISSUE THREAD

**Issue by yahiarefaiea** [Stratium/Google-Drive-for-Desktop-Integration#1]
Weeks ago, Google Drive asked me to update Backup and Sync to a new app. The old folder was called "User/{user_name}/Google Drive" and the new one was called "User/{user_name}/My Drive". And it also creates a drive partial automatically on startup that's called "Google Drive" (which's also pinned to Explorer as "Google Drive(E:)").

I used this repo before to add Google Drive to the navigation pane for easier access, but now the new version deleted the older folder and moved to new ones as described above. And with that said, the Google Drive folder is now shown on the navigation pane and can't be deleted. And when trying to open it it shows a message of "Location is not available".

I tried to remove it with the same "Remove Google Drive" registry file provided, but it doesn't seem to be working with the new version. I think the registry keys have been changed for some reason. I tried to find them before running the registry script but didn't find them.

Is there a way to fix this issue?
I really appreciate any help you can provide.

**Comment by Stratium** [comment]
Hi @yahiarefaiea
I think the issue here is that there are two versions of the Google Drive software, and two separate repositories.

I have modified the original work by Svenkle available here: https://github.com/svenkle/google-drive-add-to-explorer which was compatible with the old Backup and Sync application that you had installed.
You likely installed Svenkle's version of this repository which is not compatible with this version.

Please try running the "Remove Google Drive.reg" file available from https://github.com/svenkle/google-drive-add-to-explorer/blob/develop/Remove%20Google%20Drive.reg which should remove their version of this registry key and remove the broken navigation pane shortcut.

After this, ensure that you have "Google Drive for Desktop" installed, then run my version of this repository which should add the working shortcut again.

I hope this answers your question,
Stratium
